services:
  - cassandra

language: python

python:
  - 2.7

env:
  - CASSANDRA_DRIVER_VERSION=2.5.0
  - CASSANDRA_DRIVER_VERSION=2.6.0
  - CASSANDRA_DRIVER_VERSION=2.7.0

install:
  - pip install -q cassandra-driver==$CASSANDRA_DRIVER_VERSION
  - python setup.py -q install

script: py.test
